version: "3.4"
services:
  api:
    image: adoptopenjdk:11-jre-hotspot
    # container_name: sandbox_app_api_1
    privileged: true
    working_dir: /webapps
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./:/webapps
      - ./config/application-dev.yml:/webapps/config/application-dev.yml
    ports: 
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    command:
      - /bin/sh
      - -c
      - |
        java -jar *.jar --sprint.profiles.active=dev --server.port=8080
