version: "3.4"
services:
  api:
    image: adoptopenjdk:11-jre-hotspot
    privileged: true
    working_dir: /webapps
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./:/webapps
      - ./config/application-dev.yml:/webapps/config/application-dev.yml
    ports: 
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    # environment: 
    #    JAVA_OPTS: "$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n"
    command:
      - /bin/sh
      - -c
      - |
        java $JAVA_OPTS -jar *.jar --spring.profiles.active=test --server.port=8080
