version: "3.4"
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  redis:
    # image: 'daocloud.io/library/redis:3.2.9'
    image: redis:6.2.3
    container_name: redis
    privileged: true
    restart: always
    volumes:
      - ./redis/conf:/usr/local/etc/redis
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    ports:
      - 127.0.0.1:6379:6379

networks: 
  default:
    name: redis_default