version: "3.4"
services:
  web:
    image: daocloud.io/library/nginx:latest
    volumes: 
      - ./dist:/usr/share/nginx/html
    ports:
      - 8000:80
  
networks: 
  sandbox_default:
    external: true
