version: "3.4"
# docker-compose run --rm mvn bash
services:
  mvn:
    image: maven:3.6.0-jdk-11-slim
    working_dir: /usr/src
    volumes: 
      - ~/.m2:/root/.m2
      - ./pom.xml:/usr/src/pom.xml
      - ./src:/usr/src/src
