version: "3.4"
services:
  mysqlserver:
    image: daocloud.io/library/mysql:5.7
    container: mysqlserver
    privileged: true
    restart: always
    volumes:
       - ./mysql.conf.d/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
       - ./mysql/data:/var/lib/mysql
       - ./mysql/logs:/var/log/mysql
       - ./mysql:/mysql
       - ./mysql/tmp:/mysql/tmp
      #  - ./mall-mysql/app-data.sql:/mysql/date/init.sql
    environment:
       TZ: "Asia/Shanghai"
       MYSQL_DATABASE: test
       MYSQL_ROOT_PASSWORD: root
    logging: 
      driver: "json-file"
      options: 
        max-size: "2k"

    