version: "3"
# docker-compose -f docker-compose.yml up --detach --build   ## for recreating the change
services:
  registry:
    image: registry:2
    privileged: true
    restart: always
    volumes: 
      - /var/lib/registry:/var/lib/registry
    ports:
      - 5000:5000
