version: "3.4"
services:
  web:
    image: daocloud.io/library/nginx:latest
    privileged: true
    restart: always
    volumes: 
      - ./dist:/usr/share/nginx/html
      - ./conf.d/80.conf:/etc/nginx/conf.d/default.conf
      # - ./attachments:/usr/share/nginx/html/attachments
    ports:
      - 8000:80
  
networks: 
  sandbox_default:
    external: true
