version: "3.4"
services:
  web:
    image: nginx:stable
    privileged: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1k"    
    volumes: 
      - ./dist:/usr/share/nginx/html
      - ./config.js:/usr/share/nginx/html/config.js
      - ./conf.d/80.conf:/etc/nginx/conf.d/default.conf
      # - ./attachments:/usr/share/nginx/html/attachments
    ports:
      - 8000:80
    network_mode: net_name
