version: "3.4"
services:
  web:
    image: daocloud.io/library/nginx:latest
    volumes: 
      - ./dist:/usr/share/nginx/html
      - ./attachments:/usr/share/nginx/html/attachments
      - ./conf.d/80.conf:/etc/nginx/conf.d/80.conf
    ports:
      - 8000:80
  
networks: 
  sandbox_default:
    external: true
