version: "3.4"
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  api:
    image: sandbox-app:api  #change the api iamge
    privileged: true
    restart: always
    volumes: 
      - ./api/config/application-dev.yml:/webapps/config/application-dev.yml
    ports: 
      - 8080:8080
    networks: 
      - sandbox_default
      - mysqlserver_default
      - redis_default

  web:
    image: sandbox-app:gateway  #change the web image 
    privileged: true
    restart: always
    volumes: 
      - ./bin/attachments:/usr/share/nginx/html/attachments
      - ./gateway/conf.d/80.conf:/etc/nginx/conf.d/80.conf
    ports:
      - 8000:8000
  
networks: 
  default:
    name: sandbox_default   #change the network name
  mysqlserver_default:
    external: true
  redis_default:
    expose: true
