---
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://mysqlserver:3306/test?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: log4j,wall,mergeStat
      sql-script-encoding: UTF-8
      schema: classpath*:sql/*-schema.sql
      data: classpath*:sql/*-data.sql
      initialize: true 

logging:
  level: debug
  file: logs/access.log

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
    driver-class-name: org.h2.Driver
    username: sa
    filters: log4j,wall,mergeStat
    sql-script-encoding: UTF-8
    initialize: true

logging:
  level: debug
  file: logs/access.log
