version: "3.4"
# - ./dist:/usr/share/nginx/html
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  mysqlagent:
    image: 'daocloud.io/library/nginx:latest'
    privileged: true
    logging:
      driver: "json-file"
      options: 
        max-size: "1k"    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/mysql-expose.mod:/etc/nginx/conf.d/mysql-expose.mod
    network_mode: smartsee_default  
    ports:
      - 23336:23306
      