version: "3.4"
services:
  api:
    image: sandbox-app:api  #change 'sandbox-app' image to aplication image
    working_dir: /webapps
    volumes: 
      - ./config/application-dev.yml:/webapps/config/application-dev.yml
    ports: 
      - 8080:8080
