version: "3.4"
services:
  api:
    image: adoptopenjdk:11-jre-hotspot
    # container_name: sandbox_app_api_1
    privileged: true
    restart: always
    working_dir: /webapps
    volumes: 
      - ./api:/webapps
      - ./attachments:/webapps/attachments
      - ./config/application-dev.yml:/webapps/config/application-dev.yml
    extra_hosts: 
      - "mysqlserver:192.168.3.239"
    ports: 
      - 8080:8080
    command:
      - /bin/sh
      - -c
      - |
        java -jar *.jar --sprint.profiles.active=dev --server.port=8080
    networks: 
      - sandbox_default
      # - mysqlserver_default

networks: 
  sandbox_default:
    external: false
  # mysqlserver_default:
  #   external: false
  