version: "3.4"
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  api:
    image: app:api
    container_name: app_api
    volumes: 
      - ./api/config/application-dev.yml:/webapps/config/application-dev.yml
    ports: 
      - 8080:8080
