version: "3.4"
services:
  db: 
    image: 'daocloud.io/library/mysql:5.7'
    container_name: mysqlserver
    privileged: true
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql.conf.d/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
      # - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: 
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

networks:
  default:
    name: mysqlserver_default
